### ISSUE TITLE
[FR] Overall progress of books.

### ISSUE THREAD

**Issue by THElegend5** [mbret/oboku#16]
Being able to see overall books progress instead of just chapter progress would be nice.

**Comment by mbret** [comment]
The progress is already based on the entire book and not chapter based.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/1911240/219969319-cec456c2-3957-4d50-88de-15ea4ccaeba8.png">.

I realize it might be confusing where it is. I will move it to the bottom right and also leave it on the book (when the menu is not visible)

**Comment by THElegend5** [comment]
Didn't even know this was there but yeah this is also a nice adition, more so ment pages read out of total pages instead of just pages read out of pages in that chapter.

**Comment by mbret** [comment]
Do you have a suggestion on what to display ? I am wondering if chapter information even matter to be honest. Especially since they get confused with overall. Maybe I can show both but I should make it more straightforward which is which
