### ISSUE TITLE
[FR] Toggle to show the current time.

### ISSUE THREAD

**Issue by THElegend5** [mbret/oboku#18]
A toggle to show the current time , something like how there is one in kindle would be nice.

![Screenshot_2023-02-18-21-11-48-887-edit_com.amazon.kindle.jpg](https://user-images.githubusercontent.com/63903377/219875261-f66088d0-120e-4611-910b-82d56e70f00f.jpg)

**Comment by mbret** [comment]
available on latest release, you can reopen if something is not right
