### ISSUE TITLE
[BUG] Oboku doesn't show progress of sub level chapters with books which have parts.

### ISSUE THREAD

**Issue by THElegend5** [mbret/oboku#33]
![Screenshot_2023-03-08-12-22-26-130_org.mozilla.fenix.png](https://user-images.githubusercontent.com/63903377/223642492-76a8f322-7b13-4721-8b40-9e548847c49b.png)

![Screenshot_2023-03-08-12-24-49-030-edit_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/63903377/223642505-548fd470-b5fa-4148-9553-9b3d10258e11.jpg)

This should show chapter 16 instead of just Part 2.
Or something like Part 2 : Chapter 16.

**Comment by mbret** [comment]
should be fixed in 0.2.12
